### ISSUE TITLE
[Request] Search history and keywords

### ISSUE THREAD

**Issue by DaisyF8** [srbaber/xbmc-easynews#1]
Hi,

I don't know if you're still developing but could you add a search history ? And maybe make it possible to save keywords for repeated searches ? Your addon is a good alternative to watch daily shows.

Thx

**Comment by srbaber** [comment]
The project was more of a python learning experience than anything.  Didn't really plan on going forward with it and it uses some really old apis.   I've been using Fen from https://github.com/Tikipeter/repository.tikipeter and it has really good integration for easynews.

**Comment by DaisyF8** [comment]
Yeah I get it. I'm also a Fen user. Normally Fen will keep on working for some time now the dev has (temporarily) stopped.

Thx.

**Comment by srbaber** [comment]
Hey.  I had some downtime at work and decided to update the addon to use the latest kodi libraries.  check it out.

**Comment by DaisyF8** [comment]
Thanks 👍
