### ISSUE TITLE
Request - simpler description

### ISSUE THREAD

**Issue by sasagr** [srbaber/xbmc-easynews#30]
Hi. Very simple and nice addon. Thanks
Could it be possbile to change (maybe with an option in settings) the description of the files results with a shorter description?
For example if I search "for all mankind s03e01" I get:
FWj7a2qMNW2QoMXEZ9KiDzTBZTCnNaJVvUuj5Z7l7V66OC6rwYQ4fn2QisVG37A5 (For.All.Mankind.S03E01.720p.x265-ZMNT.mkv 573.28MB)
I would like to have the option to see only:
For.All.Mankind.S03E01.720p.x265-ZMNT.mkv 573.28MB

thanks

**Comment by srbaber** [comment]
just pushed a change to try and cleanup the titles... hopefully not too aggressive in the character removal.
should be in version 1.0.3.

Enjoy.

**Comment by sasagr** [comment]
Did not have the chance to try it but in the meantime I added this line in my local version and it seems to do the job I wanted. Up to you if you like it or not
title = re.sub('^[^(]*.', '', title)
