### ISSUE TITLE
Please update EasyNews addon to be compatible with Kodi 20

### ISSUE THREAD

**Issue by coolsudheera** [srbaber/xbmc-easynews#34]
Please update EasyNews addon to be compatible with Kodi 20. Please add a better high-quality icon for this awesome kodi EasyNews addon.

**Comment by srbaber** [comment]
I'll take a look.   Thanks for the heads up.

**Comment by srbaber** [comment]
Pushed an update.  Will work on an icon. 😁. Let me know if you find
anything running on 20.  Thanks again.

**Comment by coolsudheera** [comment]
Really grateful for you dedication to keep up this awesome kodi addon.

**Comment by Niijojik** [comment]
Greetings! I signed up for a github account today only because I am hopeful to install this repo on to my kodi 20.  Yes, I am an easy news subscriber.  I have downloaded repository.easynews-20.0.0.zip but at 179 KB it seems a bit small.  Of course, I tried to install on to kodi but it diodn't work.  Am I grabbing the correct file?  Thanks in advance!

**Comment by srbaber** [comment]
the repository points to the plugin which is the actual code...

if I remember correctly, you do install from zip on the repository:
[image: Screen Shot 2023-03-08 at 5.20.11 PM.png]
That will install the repository and you can select:
[image: Screen Shot 2023-03-08 at 5.21.04 PM.png]
[image: Screen Shot 2023-03-08 at 5.21.11 PM.png]

[image: Screen Shot 2023-03-08 at 5.21.21 PM.png]
[image: Screen Shot 2023-03-08 at 5.21.26 PM.png]

It's always confusing to me how to get the plugin installed and updated...
Kodi is not very intuitive sometimes.

**Comment by Niijojik** [comment]
Apologies, I read your response and intended to say thank you for taking time to help. Unfortunately, the images you sent came across to me as lines of text which I could not open. You're obviously very generous of your time to help others with your app. Regardless, I was not able to install on up Kodi.

Cheers!

Sent from [ProtonMail](https://protonmail.com), Swiss-based encrypted email.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by srbaber** [comment]
Not a problem at all.   There's lots of guides online for installing
repositories... Here's what I do.
1) download the repository zip:
https://github.com/srbaber/xbmc-easynews/raw/master/repository.easynews/repository.easynews-20.0.1.zip
2) install the repository: in Kodi go to settings->add ons->install from
zip file->navigate to the zip and install
3) install the add on: in Kodi go to settings->add ons->install from
repository->XBMC-easynews Addons->Video addons->Easynews.com and click the
Install button

That's it!

Don't forget when you run it to go into the add on settings (by pressing
the left arrow button on  your controller from the main menu of the
Easynews add on) to enter your id / password.
Also, you will need to enable Unknown sources settings->system->add
ons->unknown sources.   I usually turn it on/off as needed.

**Comment by Niijojik** [comment]
Again, you're so generous! Based on your response I now know what those images were for; however, I'm already familiar with Kodi's file structure and the processes for installing add-ons from zip files. Can you send me the zip file directly? I can try that way. Thank you.

Sent from [ProtonMail](https://protonmail.com), Swiss-based encrypted email.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by srbaber** [comment]
sure.  here you go.

**Comment by Niijojik** [comment]
That worked! Thank you!

Sent from [ProtonMail](https://protonmail.com), Swiss-based encrypted email.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Niijojik** [comment]
Where can I find your tip jar?

Sent from [ProtonMail](https://protonmail.com), Swiss-based encrypted email.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by WGitwood101** [comment]
is there a direct url to add to the sources in kodi so i can install the repository? ive tried multiple ways to add the github url link towards the project and can't get it to find the repository zip. I don't have the option to download the zip and install it since this is a separate device.

**Comment by srbaber** [comment]
I've got it setup... but I can never seem to get it to work:

Main landing page:
https://srbaber.github.io/xbmc-easynews/

Zip Link
https://srbaber.github.io/xbmc-easynews/repository.easynews/repository.easynews-20.0.1.zip

**Comment by Niijojik** [comment]
Kodi>Add Source did not work for me either. I had to download the zip file then upload it to my box using X-Plore File Manager which has to be installed on both devices. Turn on WiFi file sharing to transfer the zip file then use Kodi to install zip. Works great on my box.

Sent from [ProtonMail](https://protonmail.com), Swiss-based encrypted email.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by WGitwood101** [comment]
anyway to send the zip from my pc to kodi? only asking cause im using a xbox and there's not many options compared to using a fire stick or another device.

**Comment by srbaber** [comment]
I think you can use the SMB option to connect to a folder that is shared
from your pc.

[image: Screen Shot 2023-04-27 at 10.54.31 AM.png]
