### ISSUE TITLE
[bug]searching does not give all results

### ISSUE THREAD

**Issue by ghost** [srbaber/xbmc-easynews#38]
I searched for Veronica Avluv and just compared the last page on kodi to easynews and saw the results are missing.
When I change to 200 results it does show all the results.
I don't know if you still maintain this addon but if you do would appreciate if you looked into it.

edit:
I should have mentioned that I removed the Group regex filter and the File extensions in order to not limit the results.

**Comment by srbaber** [comment]
sure I can take a look this week and see what's up

thanks.

**Comment by ghost** [comment]
I wanted to also update you when I am changing it to 40 or 50 it is only removing 1 page of results while 100 removing 2 pages or 3.
Changing the number of max results can change how many last pages will be removed.
lol very weird bug.

Great to see you are still working on this addon. Really like it so thank you.

edit:
I should have mentioned that I removed the Group regex filter and the File extensions in order to not limit the results.

**Comment by srbaber** [comment]
Ok, I'm trying a different approach to pagination that won't skip pages.   Should be in version 20.0.6.  Let me know if it works better for you.   I still expect the number of items may be slightly off between kodi and web just because I do have a few things selected on the search form that you may do differently... such as -- spam filter on -- safe search off 
and if you clear the extensions field, it uses a kodi compatible list: 'AVI|MPEG|MPG|WMV|ASF|FLV|MKV|MKA|QT4|MP4|M4A|AAC|NUT|OGG|OGM|RAM|RM|RV|RA|RMVB|3GP|VIV|PVA|NUV|NSV|NSA|FLI|FLC|DVR|WTV'

let me know how it works for you.   enjoy.

**Comment by ghost** [comment]
I have tested it with 30,50,70,100,200,300,500 and 1000 max results.
I removed the Group regex filter and the File extensions in order to not limit the results.
1000 results remove the last result all the others worked fine.
Really like the thumbnails excellent work.

Bugs:
1. image filter on and video filter off gives no results. What is it suppose to do?
2. search history does not work.
3. 1000 max results remove the last result from the last page. All the others max results settings worked just fine.

Excellent work on the thumbnails and thank you very much for this addon I like it very much.

**Comment by srbaber** [comment]
the image filter and video filter are suppose to correspond to the check boxes on the advanced search screen.
for example, I can search on Star Trek with an MKV extension...
with the Video checkbox, results are 978
without the Video checkbox, results are 856
I've noticed that some files, even though they are video, aren't tagged as such.  so to get them to show up I uncheck the VIdeo filter.
The Image filter isn't so useful.  more experimental to allow me to view image thumbnails.

2.  fixed a bug
3.  I see 8858 VeronicalAvluv.mp as the last one in easynews and kodi.   What do you see?

**Comment by ghost** [comment]
The last scene is scene 4 with Jessi Palmer.
If you change it to 200 max results you will see it or on easynews website page 36.
The rest of the max results that I tested (30,50,70,100,200,300,500) are working fine.

**Comment by srbaber** [comment]
seems to be a "feature" with the easynews "remove duplicates" option.   

[[lesbo] lesbian seductions 30 older younger (scene 4 with jessi palmer) avi
and
[Scene #4 Jessi Palmer & Veronica Avluv avi]
and
[lesbian Seductions 30 s4 Jessi Palmer Veronica Avluv avi]

depending on the per/page count it removes different ones.   

but, I think overall, the number of items returned is the same.

**Comment by ghost** [comment]
It is only happen when I set it to 1000 so it is not a big of a problem anyway.
Thank you for your work on this addon.
