### ISSUE TITLE
Missing Thumbnails after search

### ISSUE THREAD

**Issue by DCWizMan** [srbaber/xbmc-easynews#52]
Hi, on the latest Kodi Omega on a NVidea Shield which is updated.   Recently after doing a search, I only get a black icon instead of the former Thumbnail view.  I thought it may be a Kodi setting but I did a fresh install and the problem persists.  Any ideas on what this maybe?

**Comment by srbaber** [comment]
looks like easynews has pushed some formatting changes to the site.
I'll have to update the scrapers to account for the new layouts.

should be able to get an update pretty quickly.

**Comment by DCWizMan** [comment]
All working now with the latest update.  Thank-you!
